version: "3"
services:
  control:
    build: ./control
    restart: on-failure
    volumes:
      - ./data/control/run:/run
    env_file:
      - config.env
    depends_on:
      - tank
  tank:
    build: ./tank
    restart: unless-stopped
    volumes:
      - ./data/tank/database:/data:Z
    env_file:
      - config.env
    ports:
      - 5432:5432

